### ISSUE TITLE
为什么运行的时候出现这个错误呢？

### ISSUE THREAD

**Issue by SpikeXy** [GiantLiu/AutoJump#1]
Error: LSTM requested, but not present!! Loading tesseract.
{"Image":{"Width":720,"Height":1440},"Top":"525, 559","Start":"227, 861","Score":7,"JumpWidth":344.10076043701696,"Time":677}

**Comment by GiantLiu** [comment]
这个是做分数识别的时候。加载的图片识别。
要在根目录下增加数字识别训练数据
tessdata/num.traineddata
